# Generated by Django 5.1.1 on 2024-09-24 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.CharField(
                        help_text="Lowercase letters, numbers, and - (hyphen) allowed.",
                        max_length=300,
                        validators=[main.validators.AlphanumericHyphenValidator()],
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("slug", "user")},
            },
        ),
    ]
