# Generated by Django 5.1.4 on 2024-12-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="email@example.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
