# Generated by Django 5.1.4 on 2024-12-24 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="title",
            new_name="website_title",
        ),
    ]
