# Generated by Django 5.1.4 on 2024-12-24 22:21

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_rename_title_user_website_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="custom_domain",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                validators=[main.validators.validate_domain_name],
            ),
        ),
    ]
