# Generated by Django 5.1.4 on 2024-12-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_user_custom_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_page",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
