# Generated by Django 5.1.4 on 2024-12-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_user_home_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="home_page",
        ),
        migrations.AddField(
            model_name="user",
            name="home",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home",
                to="main.page",
            ),
        ),
    ]
