# Generated by Django 5.1.4 on 2025-01-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_user_custom_css"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="custom_css",
            field=models.TextField(blank=True, null=True, verbose_name="Custom CSS"),
        ),
    ]
