# Generated by Django 5.1.4 on 2025-01-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact",
            field=models.BooleanField(default=False),
        ),
    ]
