# Generated by Django 5.1.4 on 2025-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_user_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact",
            field=models.BooleanField(
                default=False, verbose_name="Enable Contact page"
            ),
        ),
    ]
