# Generated by Django 5.1.6 on 2025-02-16 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_memory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="home",
        ),
    ]
