# Generated by Django 5.2 on 2025-04-12 18:54

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_remove_user_home"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="page",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="image",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="user",
            name="custom_domain",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Lowercase alphanumeric.",
                max_length=150,
                unique=True,
                validators=[
                    main.validators.AlphanumericHyphenValidator(),
                    main.validators.HyphenOnlyValidator(),
                ],
            ),
        ),
        migrations.RemoveField(
            model_name="page",
            name="user",
        ),
    ]
