# Generated by Django 5.2 on 2025-04-12 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_alter_page_unique_together_remove_image_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="website_title",
        ),
    ]
