# Generated by Django 5.2 on 2025-04-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_remove_user_website_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="landing_body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
