# Generated by Django 5.2 on 2025-04-14 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_user_landing_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="custom_css",
        ),
        migrations.RemoveField(
            model_name="user",
            name="landing_body",
        ),
    ]
