# Generated by Django 5.2 on 2025-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_remove_user_custom_css_remove_user_landing_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("introduction", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
