# Generated by Django 5.2 on 2025-04-14 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_sitesettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={"verbose_name_plural": "Site Settings"},
        ),
    ]
