# Generated by Django 5.2 on 2025-04-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_sitesettings_privacy_policy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="gender",
            field=models.CharField(
                choices=[
                    ("F", "Female"),
                    ("M", "Male"),
                    ("O", "Other"),
                    ("N", "Prefer not to say"),
                ],
                max_length=1,
            ),
        ),
    ]
