# Generated by Django 5.2 on 2025-04-15 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_alter_memory_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memory",
            options={"verbose_name_plural": "Memories"},
        ),
    ]
