# Generated by Django 5.2 on 2025-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_alter_memory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="gender",
            field=models.CharField(
                choices=[
                    ("F", "Female"),
                    ("M", "Male"),
                    ("N", "Nonbinary"),
                    ("O", "Other"),
                    ("N", "Prefer not to say"),
                ],
                max_length=1,
            ),
        ),
    ]
