# Generated by Django 5.2 on 2025-05-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_alter_memory_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="ethicity",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
