# Generated by Django 5.2 on 2025-05-23 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_memory_ethicity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memory",
            old_name="ethicity",
            new_name="ethnicity",
        ),
    ]
