# Generated by Django 5.2 on 2025-05-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_rename_ethicity_memory_ethnicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="school_grade",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="memory",
            name="school_type",
            field=models.CharField(
                choices=[
                    ("STATE", "State school"),
                    ("PRIVATE", "Private school"),
                    ("HOME", "Homeschooling"),
                    ("COLLEGE", "College"),
                    ("MONTESSORI", "Montessori school"),
                    ("BOARDING", "Boarding school"),
                    ("RELIGIOUS", "Religious school"),
                    ("VOCATIONAL", "Vocational education"),
                ],
                max_length=100,
            ),
        ),
    ]
