# Generated by Django 5.2 on 2025-05-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_alter_memory_school_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="school_type",
            field=models.CharField(
                choices=[
                    ("STATE", "State School"),
                    ("PRIVATE", "Private School"),
                    ("HOME", "Homeschooling"),
                    ("COLLEGE", "College"),
                    ("MONTESSORI", "Montessori School"),
                    ("BOARDING", "Boarding School"),
                    ("RELIGIOUS", "Religious School"),
                    ("VOCATIONAL", "Vocational Education"),
                    ("OTHER", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
