# Generated by Django 5.2 on 2025-05-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_alter_memory_school_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="school_type_other",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
