# Generated by Django 5.2 on 2025-05-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_memory_school_type_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="memory_themes",
            field=models.CharField(
                default="", help_text="Comma-separated memory themes", max_length=500
            ),
            preserve_default=False,
        ),
    ]
