# Generated by Django 5.2 on 2025-05-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_memory_memory_themes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="memory_themes",
            field=models.CharField(
                help_text="Comma-separated memory themes", max_length=20
            ),
        ),
    ]
