# Generated by Django 5.2 on 2025-05-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0033_alter_memory_memory_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="custom_themes",
            field=models.CharField(
                blank=True,
                help_text="User-provided custom themes, separated by semicolons",
                max_length=500,
                null=True,
            ),
        ),
    ]
