# Generated by Django 5.2 on 2025-05-23 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0034_memory_custom_themes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memory",
            old_name="custom_themes",
            new_name="memory_themes_additional",
        ),
    ]
