# Generated by Django 5.2 on 2025-05-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0035_rename_custom_themes_memory_memory_themes_additional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="memory_themes",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="memory",
            name="memory_themes_additional",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
