# Generated by Django 5.2 on 2025-05-23 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0036_alter_memory_memory_themes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memory",
            name="category",
        ),
        migrations.RemoveField(
            model_name="memory",
            name="tags",
        ),
    ]
