# Generated by Django 5.2 on 2025-05-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0037_remove_memory_category_remove_memory_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="gender",
            field=models.CharField(
                choices=[
                    ("F", "Female"),
                    ("M", "Male"),
                    ("N", "Nonbinary"),
                    ("O", "Other"),
                    ("P", "Prefer not to say"),
                ],
                max_length=1,
            ),
        ),
    ]
