# Generated by Django 5.2 on 2025-05-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0038_alter_memory_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="code",
            field=models.IntegerField(default=0),
        ),
    ]
