# Generated by Django 5.2 on 2025-05-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0039_memory_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
