# Generated by Django 5.2 on 2025-10-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_memory_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='ethnicity',
            new_name='heritage',
        ),
        migrations.AddField(
            model_name='memory',
            name='age',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')], default=10),
        ),
        migrations.AddField(
            model_name='memory',
            name='gender_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='gender',
            field=models.CharField(choices=[('BOY', 'Boy'), ('GIRL', 'Girl'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='PREFER_NOT_TO_SAY', max_length=20),
        ),
    ]
