# Generated by Django 5.2 on 2025-10-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_rename_ethnicity_memory_heritage_memory_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='school_type_other',
            new_name='religious_tradition',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='school_type',
        ),
        migrations.AddField(
            model_name='memory',
            name='educational_philosophy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='educational_philosophy_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='location',
            field=models.CharField(default='Not specified', help_text='City/town/village', max_length=200),
        ),
        migrations.AddField(
            model_name='memory',
            name='religious_tradition_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='school_funding',
            field=models.CharField(choices=[('GOVERNMENT_STATE', 'Government/State'), ('FAMILY', 'Family'), ('SCHOLARSHIP_DONATIONS', 'Scholarship/Donations'), ('OTHER', 'Other')], default='GOVERNMENT_STATE', max_length=100),
        ),
        migrations.AddField(
            model_name='memory',
            name='school_funding_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
