# Generated by Django 5.2 on 2025-10-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0043_alter_memory_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="religious_tradition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("QUAKER", "Quaker"),
                    ("CATHOLIC", "Catholic"),
                    ("PROTESTANT_CHRISTIAN", "Protestant/Christian"),
                    ("JEWISH", "Jewish"),
                    ("MUSLIM", "Muslim"),
                    ("HINDU", "Hindu"),
                    ("BUDDHIST", "Buddhist"),
                    ("GREEK_ORTHODOX", "Greek Orthodox"),
                    ("DOES_NOT_APPLY", "Does not apply"),
                    ("OTHER", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
