# Generated by Django 5.2 on 2025-10-21 08:48

from django.db import migrations


def fix_empty_educational_philosophy(apps, schema_editor):
    """Fix records where educational_philosophy is stored as '[]' instead of None."""
    Memory = apps.get_model('main', 'Memory')
    # Update records where educational_philosophy is '[]' or empty string to None
    Memory.objects.filter(educational_philosophy__in=['[]', '']).update(educational_philosophy=None)


def reverse_fix(apps, schema_editor):
    """No need to reverse this data migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_memory_religious_tradition'),
    ]

    operations = [
        migrations.RunPython(fix_empty_educational_philosophy, reverse_fix),
    ]
